.PHONY: clean All

All:
	@echo "----------Building project:[ dfu_tools - Debug ]----------"
	@cd "/mnt/c/Glydways/bl_tools/dfu_tools" && "$(MAKE)" -f  "dfu_tools.mk"
clean:
	@echo "----------Cleaning project:[ dfu_tools - Debug ]----------"
	@cd "/mnt/c/Glydways/bl_tools/dfu_tools" && "$(MAKE)" -f  "dfu_tools.mk" clean
